### ISSUE TITLE
type object is not subscriptable

### ISSUE THREAD

**Issue by daemitus** [sauldom102/gql_schema_codegen#1]
```
/gql_schema_codegen/schema/schema.py", line 43, in Schema
def config_file_content(self) -> Optional[dict[str, str]]:
```

Saw a few others while I was there.

**Comment by fernandogrd** [comment]
This is likely due to python version, as that syntax is only supported in recent versions.

**Comment by daemitus** [comment]
Oh, new features, love it :D

I must have still been on my ancient 3.7/3.8 venv.

**Comment by sauldom102** [comment]
Yes, as @fernandogrd is pointing out that's likely due to the python version you're using that doesn't support that typing
